### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by zlo2k** [delletenebre/xbmc-addon-kilogramme#5]
Добрый день, в ts.kg, есть ошибка, не знаю как исправить .. .не отображает список серий если названия на русском (не латиница) ...

**Comment by zlo2k** [comment]
Увидел, коммит :) только вот зипа для обновления нет :)

**Comment by delletenebre** [comment]
Объединено в 1.5.7, zip размещён (3 день как), проверьте.

**Comment by zlo2k** [comment]
Да я вчера все по новой заинсталил, все свежее накатилось ... просто коди что-то тупил и новую не качал :)
